# Generated by Django 3.0.7 on 2021-10-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211019_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='chat_preference',
            field=models.CharField(choices=[('0', 'ChatApp'), ('1', 'Llamada'), ('2', 'Ambas')], default='', max_length=1),
        ),
    ]
