# Generated by Django 3.0.7 on 2021-10-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20211019_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='type',
            new_name='type_status',
        ),
    ]
