# Generated by Django 3.0.7 on 2021-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211020_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre'),
        ),
    ]
