# Generated by Django 3.0.7 on 2021-10-22 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20211021_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cases_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RUT', to='usuarios.Teacher'),
        ),
    ]
