# Generated by Django 3.0.7 on 2021-10-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_case_cases_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cases_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RUT', to='usuarios.Client'),
            preserve_default=False,
        ),
    ]
