# Generated by Django 3.0.7 on 2021-10-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20211021_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='usuarios.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='usuarios.Teacher'),
            preserve_default=False,
        ),
    ]
