# Generated by Django 3.0.7 on 2021-11-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20211023_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_client',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_teacher',
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Teacher'),
        ),
    ]
