# Generated by Django 3.0.7 on 2021-11-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20211106_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='files',
            field=models.FileField(null=True, upload_to='documents/cases/'),
        ),
    ]
